FROM ubuntu:18.04 as builder-stage

ENV DEBIAN_FRONTEND noninteractive

# for CMAKE

RUN apt update && apt full-upgrade -y && \
  apt install --no-install-recommends -y software-properties-common && \
  add-apt-repository -y ppa:ubuntu-toolchain-r/test && \
  apt install -y --no-install-recommends \
  unzip \
  curl \
  make \
  git \
  zlib1g-dev \
  ca-certificates \
  mesa-common-dev \
  libglu1-mesa-dev \
  gcc-9 \
  g++-9 \
  python3-pip && \
  apt-get clean && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

# install cmake
RUN apt update && apt full-upgrade -y && \
  apt install -y --no-install-recommends cmake ninja-build

#install Qt6
RUN pip install aqtinstall && aqt install-qt linux desktop 6.5.3 -m qtcharts qtopengl --outputdir /opt/qt6

ENV QTDIR="/opt/qt6/6.5.3/gcc_64"
ENV PATH="$QTDIR/bin:$PATH"
ENV LD_LIBRARY_PATH="$QTDIR/lib:$LD_LIBRARY_PATH"

