FROM ubuntu:22.04 as builder-stage

ENV DEBIAN_FRONTEND noninteractive

# Prepare environment
RUN apt update && apt upgrade -y && \
  apt install -y \
  unzip \
  curl \
  cmake \
  ninja-build \
  git \
  zlib1g-dev \
  libglu1-mesa-dev \
  qt6-base-dev \
  libqt6charts6-dev \
  libqt6opengl6-dev \
  qt6-image-formats-plugins \
  nvidia-cuda-toolkit \
  nvidia-cuda-dev \
  nvidia-cuda-toolkit-gcc \
  gcc-12 \
  g++-12 && \
  apt-get -y autoremove --purge && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*
