FROM nvidia/cuda:11.8.0-devel-ubuntu22.04 as builder-stage

ENV DEBIAN_FRONTEND noninteractive

# Prepare environment
RUN apt update && apt upgrade -y && \
  apt install -y \
  unzip \
  curl \
  git \
  zlib1g-dev \
  libglu1-mesa-dev \
  qt6-base-dev \
  libqt6charts6-dev \
  libqt6opengl6-dev \
  qt6-image-formats-plugins \
  gcc-11 \
  g++-11 && \
  apt-get -y autoremove --purge && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

RUN update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-11 100 && update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-11 100

# install updated cmake 
RUN curl -fsSL https://apt.kitware.com/kitware-archive.sh | bash
RUN apt install -y --no-install-recommends cmake ninja-build

