FROM ubuntu:22.04 as builder-stage

ENV DEBIAN_FRONTEND noninteractive

# Prepare environment
RUN apt update && apt upgrade -y && \
  apt install -y \
  unzip \
  curl \
  git \
  zlib1g-dev \
  libglu1-mesa-dev \
  qt6-base-dev \
  libqt6charts6-dev \
  libqt6opengl6-dev \
  qt6-image-formats-plugins \
  nvidia-cuda-toolkit \
  nvidia-cuda-dev \
  nvidia-cuda-toolkit-gcc \
  gcc-10 \
  g++-10 && \
  apt-get -y autoremove --purge && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

# downgrade gcc/g++ to 10 due to issue with nvcc: https://github.com/NVlabs/instant-ngp/issues/119
RUN update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-10 100 && update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-10 100

# install updated cmake 
RUN curl -fsSL https://apt.kitware.com/kitware-archive.sh | bash
RUN apt install -y --no-install-recommends cmake ninja-build

