FROM ubuntu:18.04 as builder-stage

ENV DEBIAN_FRONTEND noninteractive

# Prepare environment
# We use a ppa for the qt because 18.04 is too old for DSI
RUN apt update && apt full-upgrade -y && \
  apt install --no-install-recommends -y software-properties-common && \
  add-apt-repository -y ppa:beineri/opt-qt-5.12.8-bionic && \
  add-apt-repository -y ppa:ubuntu-toolchain-r/test && \
  apt install -y --no-install-recommends \
  unzip \
  curl \
  make \
  git \
  zlib1g-dev \
  ca-certificates \
  qt512base \
  qt512charts-no-lgpl \
  mesa-common-dev \
  libglu1-mesa-dev \
  gcc-9 \
  g++-9 && \
  apt-get clean && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*


RUN update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-9 \
                    99 \
                    --slave   /usr/bin/cc cc /usr/bin/gcc-9 \
                    --slave   /usr/bin/c++ c++ /usr/bin/g++-9 \
                    --slave   /usr/bin/g++ g++ /usr/bin/g++-9 \
                    --slave   /usr/bin/gcov gcov /usr/bin/gcov-9 \
                    --slave   /usr/bin/gcov-dump gcov-dump /usr/bin/gcov-dump-9 \
                    --slave   /usr/bin/gcov-tool gcov-tool /usr/bin/gcov-tool-9 \
                    --slave   /usr/bin/gcc-ar gcc-ar /usr/bin/gcc-ar-9 \
                    --slave   /usr/bin/gcc-nm gcc-nm /usr/bin/gcc-nm-9 \
                    --slave   /usr/bin/gcc-ranlib gcc-ranlib /usr/bin/gcc-ranlib-9

RUN update-alternatives --auto gcc