FROM sickcodes/docker-osx:monterey as builder-stage

# Install Brew
RUN /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)" 

ENV PATH="/home/linuxbrew/.linuxbrew/bin:${PATH}"

RUN brew update && brew install qt5 && brew install git && brew install glew

ENV PATH="/home/linuxbrew/.linuxbrew/opt/qt@5/bin:${PATH}"

ENV LDFLAGS="-L/home/linuxbrew/.linuxbrew/opt/qt@5/lib"
ENV CPPFLAGS="-I/home/linuxbrew/.linuxbrew/opt/qt@5/include"
ENV PKG_CONFIG_PATH="/home/linuxbrew/.linuxbrew/opt/qt@5/lib/pkgconfig"