FROM sickcodes/docker-osx:monterey as builder-stage

# Install Qt5
RUN /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)" && brew update && brew install qt5



