FROM redhat/ubi8:8.10-1020 as builder-stage

# Prepare environment
RUN dnf update -y && \
  dnf install -y \
  unzip \
  curl \
  cmake \
  ninja-build \
  git \
  zlib-devel \
  gcc \
  gcc-c++ \
  python3 python3-pip && \
  dnf clean all && rm -rf /var/cache/yum

RUN pip3 install --upgrade pip
RUN pip3 install aqtinstall
RUN aqt install-qt linux desktop 6.5 -m qtcharts

