FROM redhat/ubi8:8.10-1020 as builder-stage

# Prepare environment
RUN dnf update -y && \
  dnf install -y \
  unzip \
  curl \
  cmake \
  ninja-build \
  git \
  zlib-devel \
  gcc \
  gcc-c++ \
  xcb-util-cursor && \
  dnf clean all && rm -rf /var/cache/yum


# Get Qt 6
RUN pip install aqtinstall
RUN aqt install-qt linux desktop 6.5 -m qtcharts

