name: Build
on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag'
        required: true
        default: '2025.04.16'
      build_windows:
        type: boolean
        description: 'Build Windows'
        required: false
        default: 'true'
      build_linux:
        type: boolean
        description: 'Build Linux'
        required: false
        default: 'true'
      build_linux_arm:
        type: boolean
        description: 'Build Linux (Arm64)'
        required: false
        default: 'true'
      build_mac:
        type: boolean
        description: 'Build Mac'
        required: false
        default: 'true'
      build_docker:
        type: boolean
        description: 'Build Docker'
        required: false
        default: 'true'
 
jobs:    

  linux-build:
    if: ${{ github.event.inputs.build_linux == 'true' }}
    strategy:
      matrix:
        os: [ubuntu2404,ubuntu2204,ubuntu2004]
      fail-fast: false
    runs-on: ubuntu-latest
    steps:
    - name: Download Build
      run: |
        git clone https://x-access-token:${{ secrets.DSISTUDIO_TOKEN }}@github.com/frankyeh/DSI-Studio-Build.git  
        mv DSI-Studio-Build/build_packages .
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3.0.0
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3.0.0
    - name: Build and push
      uses: docker/build-push-action@v5.1.0
      with:
        context: .
        build-args: |
          DSISTUDIO_TOKEN=${{ secrets.DSISTUDIO_TOKEN }}        
        file: build_packages/${{ matrix.os }}/Dockerfile
        push: false
        outputs: dsi-studio-cpu
    - name: Build and push
      uses: docker/build-push-action@v5.1.0
      with:
        context: .
        build-args: |
          DSISTUDIO_TOKEN=${{ secrets.DSISTUDIO_TOKEN }}        
        file: build_packages/${{ matrix.os }}/Dockerfile_cuda
        push: false
        outputs: dsi-studio
    - name: Packaging
      run: |
        zip -r dsi_studio_${{ matrix.os }}_cpu.zip dsi-studio-cpu
        zip -r dsi_studio_${{ matrix.os }}.zip dsi-studio
    - name: Create Release
      env:
        GH_TOKEN: ${{ secrets.DSISTUDIO_TOKEN }}
      run: |
        gh release upload ${{ github.event.inputs.tag }} *.zip --clobber --repo frankyeh/DSI-Studio

  linux-build-arm:
    if: ${{ github.event.inputs.build_linux_arm == 'true' }}
    strategy:
      matrix:
        os: [ubuntu2404,ubuntu2204]
      fail-fast: false
    runs-on: ubuntu-24.04-arm
    steps:
    - name: Download Build
      run: |
        git clone https://x-access-token:${{ secrets.DSISTUDIO_TOKEN }}@github.com/frankyeh/DSI-Studio-Build.git  
        mv DSI-Studio-Build/build_packages .
    - name: Prepare Dockerfile for ARM build (CPU)
      run: |
        DOCKERFILE_PATH="build_packages/${{ matrix.os }}/Dockerfile"
        echo "Modifying Dockerfile: $DOCKERFILE_PATH"
        # 1. Modify the FROM line to use the _arm base image
        sed -i '1s|\(:latest as builder-stage\)$|_arm\1|' "$DOCKERFILE_PATH"
        # 2. Modify the linuxdeployqt download URL to use the aarch64 version
        # This replaces 'x86_64.AppImage' with 'aarch64.AppImage' in the download URL.
        sed -i 's|linuxdeployqt-continuous-x86_64.AppImage|linuxdeployqt-continuous-aarch64.AppImage|' "$DOCKERFILE_PATH"
        echo "Modified Dockerfile content:"
        cat "$DOCKERFILE_PATH"
    - name: Prepare Dockerfile for ARM build (CUDA)
      run: |
        DOCKERFILE_PATH="build_packages/${{ matrix.os }}/Dockerfile_cuda"
        echo "Modifying Dockerfile: $DOCKERFILE_PATH"
        # 1. Modify the FROM line to use the _arm base image
        sed -i '1s|\(:latest as builder-stage\)$|_arm\1|' "$DOCKERFILE_PATH"
        # 2. Modify the linuxdeployqt download URL to use the aarch64 version
        # This replaces 'x86_64.AppImage' with 'aarch64.AppImage' in the download URL.
        sed -i 's|linuxdeployqt-continuous-x86_64.AppImage|linuxdeployqt-continuous-aarch64.AppImage|' "$DOCKERFILE_PATH"
        echo "Modified Dockerfile content:"
        cat "$DOCKERFILE_PATH"

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3.0.0
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3.0.0
    - name: Build and push (CPU)
      uses: docker/build-push-action@v5.1.0
      with:
        context: .
        build-args: |
          DSISTUDIO_TOKEN=${{ secrets.DSISTUDIO_TOKEN }}        
        file: build_packages/${{ matrix.os }}/Dockerfile
        push: false
        outputs: dsi-studio-cpu
    - name: Build and push (CUDA)
      uses: docker/build-push-action@v5.1.0
      with:
        context: .
        build-args: |
          DSISTUDIO_TOKEN=${{ secrets.DSISTUDIO_TOKEN }}        
        file: build_packages/${{ matrix.os }}/Dockerfile_cuda
        push: false
        outputs: dsi-studio
    - name: Packaging
      run: |
        zip -r dsi_studio_${{ matrix.os }}_cpu_arm64.zip dsi-studio-cpu
        zip -r dsi_studio_${{ matrix.os }}_arm64.zip dsi-studio
    - name: Create Release
      env:
        GH_TOKEN: ${{ secrets.DSISTUDIO_TOKEN }}
      run: |
        gh release upload ${{ github.event.inputs.tag }} *.zip --clobber --repo frankyeh/DSI-Studio

  macos-build:
    if: ${{ github.event.inputs.build_mac == 'true' }}
    strategy:
      matrix:
        os: [macos-14,macos-13,macos-15]
      fail-fast: false
    runs-on: ${{ matrix.os }}
    env:
      CFLAGS: -Werror
    steps:
    - uses: actions/checkout@v4.1.1
    - name: Download Build
      run: |
        git clone https://x-access-token:${{ secrets.DSISTUDIO_TOKEN }}@github.com/frankyeh/DSI-Studio-Build.git  
        mv DSI-Studio-Build/*.txt .
        mv DSI-Studio-Build/build_packages/build_mac.sh .
    - name: brew update
      run: |
        brew update
        brew uninstall cmake
        brew install cmake
    - name: Install Qt
      uses: jurplel/install-qt-action@v4.1.1
      with:
        version: 6.8    
        modules: qtcharts
        cache: true
    - name: Build DSI Studio
      run: |
        sh build_mac.sh ${{ matrix.os }}
        zip -r dsi_studio_${{ matrix.os }}_qt6.zip dsi_studio.app
    - name: Create Release
      env:
        GH_TOKEN: ${{ secrets.DSISTUDIO_TOKEN }}
      run: |
        gh release upload ${{ github.event.inputs.tag }} *.zip --clobber 

  docker_build:
    if: ${{ github.event.inputs.build_docker == 'true' }}
    runs-on: ubuntu-latest
    steps:
    - name: Download Build
      run: |
        git clone https://x-access-token:${{ secrets.DSISTUDIO_TOKEN }}@github.com/frankyeh/DSI-Studio-Build.git  
        mv DSI-Studio-Build/build_packages .
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3.0.0
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3.0.0
    - name: Login to DockerHub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Current Time
      run: echo "DATE_TAG=$(date "+%Y-%m-%d")" >> $GITHUB_ENV
    - name: Build and push
      uses: docker/build-push-action@v5.1.0
      with:
        context: .
        build-args: |
          DSISTUDIO_TOKEN=${{ secrets.DSISTUDIO_TOKEN }}               
        file: build_packages/docker/Dockerfile
        push: true
        tags: |
          "dsistudio/dsistudio:hou-${{ env.DATE_TAG }}"
          dsistudio/dsistudio:latest

  windows_build_cpu:
    if: ${{ github.event.inputs.build_windows == 'true' }}
    runs-on:  windows-latest
    steps:
    - uses: actions/checkout@v4.1.1
    - name: Download Build
      run: |
        git clone https://x-access-token:${{ secrets.DSISTUDIO_TOKEN }}@github.com/frankyeh/DSI-Studio-Build.git  
        move DSI-Studio-Build/*.txt .
        move DSI-Studio-Build/build_packages .
    - name: Install Qt
      uses: Kidev/install-qt-action@v4.6.0
      with:
        modules: qtcharts
        cache: true
    - name: Build
      run: |
        call .\build_packages\build_win.bat
        if exist "dsi_studio_win\dsi_studio.exe" (
          echo "dsi_studio.exe exists!"
        ) else (
          echo "Error: dsi_studio.exe not found!" >&2
          exit /b 1
        )
        move dsi_studio_win.zip dsi_studio_win_cpu.zip
      shell: cmd
    - name: Create Release
      env:
        GH_TOKEN: ${{ secrets.DSISTUDIO_TOKEN }}
      run: |
        gh release upload ${{ github.event.inputs.tag }} dsi_studio_win_cpu.zip --clobber

  windows_build:
    if: ${{ github.event.inputs.build_windows == 'true' }}
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4.1.1
    - name: Download Build
      run: |
        git clone https://x-access-token:${{ secrets.DSISTUDIO_TOKEN }}@github.com/frankyeh/DSI-Studio-Build.git  
        move DSI-Studio-Build/*.txt .
        move DSI-Studio-Build/build_packages .
    - name: Install Cuda
      uses: Jimver/cuda-toolkit@v0.2.23
    - name: Install Qt
      uses: Kidev/install-qt-action@v4.6.0
      with:
        modules: qtcharts
        cache: true
    - name: Build
      run: |
        call .\build_packages\build_win.bat
        if exist "dsi_studio_win\dsi_studio.exe" (
          echo "dsi_studio.exe exists!"
        ) else (
          echo "Error: dsi_studio.exe not found!" >&2
          exit /b 1
        )
      shell: cmd
    - name: Create Release
      env:
        GH_TOKEN: ${{ secrets.DSISTUDIO_TOKEN }}
      run: |
        gh release upload ${{ github.event.inputs.tag }} dsi_studio_win.zip --clobber        
        
          
