name: DICOM DWI Test

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  linux-build:
    name: Linux build
    runs-on: ubuntu-latest
    steps:
      - name: Download Build
        run: |
          git clone --depth 1 https://x-access-token:${{ secrets.DSISTUDIO_TOKEN }}@github.com/frankyeh/DSI-Studio-Build.git
          mv DSI-Studio-Build/build_packages .

      - uses: docker/setup-qemu-action@v3.0.0
      - uses: docker/setup-buildx-action@v3.0.0

      - name: Build Linux
        uses: docker/build-push-action@v5.1.0
        with:
          context: .
          build-args: |
            DSISTUDIO_TOKEN=${{ secrets.DSISTUDIO_TOKEN }}
          file: build_packages/ubuntu2404/Dockerfile
          push: false
          outputs: dsi-studio

      - uses: actions/upload-artifact@v4
        with:
          name: dsi_studio_linux
          path: dsi-studio

  dicom-test:
    name: ${{ matrix.dataset }} - ${{ matrix.input }}
    needs: linux-build
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - dataset: dcm_qa_dti
            input: In/Prisma
          - dataset: dcm_qa_philips
            input: In/Bangalore_2008/dwi_no-phi
          - dataset: dcm_qa_philips
            input: In/Rosetta_2013/1101
          - dataset: dcm_qa_philips
            input: In/Vanderbilt_2018/601_WIP_dti_ax
          - dataset: dcm_qa_philips_dwi
            input: In/cl/DICOM
          - dataset: dcm_qa_philips_dwi
            input: In/enh/DICOM
          - dataset: dcm_qa_sag
            input: In/4_DWI_SagAPmosaic
          - dataset: dcm_qa_sag
            input: In/5_DWI_SagHFmosaic
          - dataset: dcm_qa_sag
            input: In/6_DWI_SagAP
          - dataset: dcm_qa_sag
            input: In/7_DWI_SagHF
          - dataset: dcm_qa_xa30
            input: In/10_DWI_dir80_PA
          - dataset: dcm_qa_xa30
            input: In/17_DWI_dir80_AP
          - dataset: dcm_qa_xa30i
            input: In/11001_DWI_dir80_AP

    steps:
      - name: Download DSI Studio
        uses: actions/download-artifact@v4
        with:
          name: dsi_studio_linux
          path: dsi-studio

      - name: Prepare DSI Studio
        run: |
          chmod +x dsi-studio/dsi_studio
          echo "$PWD/dsi-studio" >> "$GITHUB_PATH"

      - name: Download ${{ matrix.dataset }}
        run: |
          git clone --depth 1 \
            https://github.com/neurolabusc/${{ matrix.dataset }}.git data

      - name: Test ${{ matrix.dataset }} - ${{ matrix.input }}
        run: |
          set -euxo pipefail

          input="data/${{ matrix.input }}"
          find "$input" -type f -name '*.gz' -exec gzip -d {} +

          dsi_studio --action=ren --source="$input"
          dsi_studio --action=src --source="$input"
