name: DICOM DWI Test

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  linux-build:
    name: Linux build
    runs-on: ubuntu-latest
    steps:
      - name: Download Build
        run: |
          git clone --depth 1 https://x-access-token:${{ secrets.DSISTUDIO_TOKEN }}@github.com/frankyeh/DSI-Studio-Build.git
          mv DSI-Studio-Build/build_packages .

      - uses: docker/setup-qemu-action@v3.0.0
      - uses: docker/setup-buildx-action@v3.0.0

      - name: Build Linux
        uses: docker/build-push-action@v5.1.0
        with:
          context: .
          build-args: |
            DSISTUDIO_TOKEN=${{ secrets.DSISTUDIO_TOKEN }}
          file: build_packages/ubuntu2404/Dockerfile
          push: false
          outputs: dsi-studio

      - uses: actions/upload-artifact@v4
        with:
          name: dsi_studio_linux
          path: dsi-studio

  dicom-test:
    name: ${{ matrix.dataset }}
    needs: linux-build
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - dataset: dcm_qa_dti
            inputs: In/Prisma
          - dataset: dcm_qa_philips
            inputs: In/Bangalore_2008/dwi_no-phi In/Rosetta_2013/1101 In/Vanderbilt_2018/601_WIP_dti_ax
          - dataset: dcm_qa_philips_dwi
            inputs: In/cl/DICOM In/enh/DICOM
          - dataset: dcm_qa_sag
            inputs: In/4_DWI_SagAPmosaic In/5_DWI_SagHFmosaic In/6_DWI_SagAP In/7_DWI_SagHF
          - dataset: dcm_qa_xa30
            inputs: In/10_DWI_dir80_PA In/11_DWI_dir80_PA In/12_DWI_dir80_PA In/13_DWI_dir80_PA In/14_DWI_dir80_PA In/15_DWI_dir80_PA In/16_DWI_dir80_PA In/17_DWI_dir80_AP In/18_DWI_dir80_AP In/19_DWI_dir80_AP In/20_DWI_dir80_AP In/21_DWI_dir80_AP In/22_DWI_dir80_AP In/23_DWI_dir80_AP In/24_DWI_dir80_AP
          - dataset: dcm_qa_xa30i
            inputs: In/11001_DWI_dir80_AP In/12001_DWI_dir80_AP In/13001_DWI_dir80_AP In/14001_DWI_dir80_AP In/15001_DWI_dir80_AP In/16_DWI_dir80_AP In/17001_DWI_dir80_AP

    steps:
      - name: Download DSI Studio
        uses: actions/download-artifact@v4
        with:
          name: dsi_studio_linux
          path: dsi-studio

      - name: Prepare DSI Studio
        run: |
          chmod +x dsi-studio/dsi_studio
          echo "$PWD/dsi-studio" >> "$GITHUB_PATH"

      - name: Download ${{ matrix.dataset }}
        run: |
          git clone --depth 1 \
            https://github.com/neurolabusc/${{ matrix.dataset }}.git data

      - name: Test ${{ matrix.dataset }}
        run: |
          set -euxo pipefail

          for path in ${{ matrix.inputs }}; do
            input="data/$path"
            find "$input" -type f -name '*.gz' -exec gzip -d {} +

            rm -rf "$RUNNER_TEMP/dicom_ren"
            cp -a "$input" "$RUNNER_TEMP/dicom_ren"

            dsi_studio --action=src --source="$input"
            dsi_studio --action=ren --source="$RUNNER_TEMP/dicom_ren"
          done
